"""
compliance_checker.py
======================
AI Compliance Checker module for the CricScope-style hackathon project
(data-center EPC document set generated by fill_data.py).
"""

import os
import re
import gc
import argparse
import pandas as pd

try:
    import pdfplumber
except ImportError:
    pdfplumber = None

try:
    import fitz  # PyMuPDF -- pure pip install, no external binary needed
except ImportError:
    fitz = None

try:
    import easyocr
    # Loaded once and reused across every OCR call -- loading it per-file
    # would re-read the model weights from disk every time, which is slow
    # and, on constrained machines, can exhaust memory.
    _EASYOCR_READER = None
except ImportError:
    easyocr = None
    _EASYOCR_READER = None


def _get_easyocr_reader():
    global _EASYOCR_READER
    if _EASYOCR_READER is None and easyocr is not None:
        print("  [ocr] Loading OCR model (first call only, may take a moment)...")
        _EASYOCR_READER = easyocr.Reader(["en"], gpu=False, verbose=False)
    return _EASYOCR_READER


def extract_pdf_text(pdf_path, ocr_min_chars=50, ocr_dpi=100):
    text = ""
    if pdfplumber is not None:
        try:
            with pdfplumber.open(pdf_path) as pdf:
                pages_text = [p.extract_text() or "" for p in pdf.pages]
                text = "\n".join(pages_text).strip()
        except Exception:
            text = ""

    if len(text) >= ocr_min_chars:
        return text, "text_layer"

    if fitz is None or easyocr is None:
        return text, "text_layer"

    reader = _get_easyocr_reader()
    if reader is None:
        return text, "text_layer"

    ocr_text_parts = []
    try:
        doc = fitz.open(pdf_path)
        zoom = ocr_dpi / 72.0
        mat = fitz.Matrix(zoom, zoom)
        for page in doc:
            pix = page.get_pixmap(matrix=mat)
            img_path = pdf_path + ".__ocr_tmp.png"
            pix.save(img_path)
            del pix
            try:
                result = reader.readtext(img_path, detail=0, paragraph=True)
                ocr_text_parts.append("\n".join(result))
                del result
            finally:
                if os.path.exists(img_path):
                    os.remove(img_path)
            gc.collect()
        doc.close()
    except Exception as e:
        return text, "text_layer"

    ocr_text = "\n".join(ocr_text_parts).strip()
    if len(ocr_text) > len(text):
        return ocr_text, "ocr"
    return text, "text_layer"


def _search(pattern, text, flags=re.IGNORECASE):
    m = re.search(pattern, text, flags)
    return m


def extract_ups_efficiency(text):
    m = _search(r"efficiency of\s*([\d.]+)\s*percent", text)
    if not m:
        m = _search(r"efficiency[^0-9]{0,15}([\d.]+)\s*%", text)
    if m:
        return {"found": True, "value": float(m.group(1)), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_ups_voltage(text):
    m = _search(r"(\d{3})V,?\s*(\d+)Hz|(\d{3})V.*?3-Phase", text)
    if m or "415V" in text.replace(" ", ""):
        m2 = _search(r"415\s*V", text)
        if m2:
            return {"found": True, "value": "415V 3-Phase 50Hz", "raw_evidence": m2.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_ups_topology(text):
    m = _search(r"tier\s*iii|concurrently maintainable|double conversion", text)
    if m:
        return {"found": True, "value": m.group(0), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_chiller_draw(text):
    m = _search(r"peak power draw of\s*([\d.]+)\s*kW", text)
    if not m:
        m = _search(r"([\d.]+)\s*kW", text)
    if m:
        return {"found": True, "value": float(m.group(1)), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_chiller_supply_temp(text):
    m = _search(r"([\d.]+)\s*C\s*design target|target of\s*([\d.]+)\s*C|meets the\s*([\d.]+)\s*C", text)
    if m:
        val = next(g for g in m.groups() if g)
        return {"found": True, "value": float(val), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_chiller_redundancy(text):
    if re.search(r"n\+1", text, re.IGNORECASE) and "upgrade" not in text.lower():
        return {"found": True, "value": "N+1", "raw_evidence": "N+1 stated"}
    if re.search(r"upgrade module|field-installed upgrade", text, re.IGNORECASE):
        return {"found": True, "value": "N (upgrade available)", "raw_evidence": "N base + chargeable N+1 upgrade"}
    if re.search(r"single n unit|ships as a single n", text, re.IGNORECASE):
        return {"found": True, "value": "N", "raw_evidence": "Single N unit"}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_gen_transfer_time(text):
    m = _search(r"within\s*([\d.]+)\s*seconds", text)
    if m:
        return {"found": True, "value": float(m.group(1)), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_gen_speed(text):
    m = _search(r"(\d{3,4})\s*RPM", text)
    if m:
        return {"found": True, "value": f"{m.group(1)} RPM", "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_gen_emissions(text):
    m = _search(r"CPCB[-\s]?IV\+|emission[s]?\s*(certif\w*|complian\w*)", text)
    if m and re.search(r"CPCB", text, re.IGNORECASE):
        return {"found": True, "value": m.group(0), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_batt_autonomy(text):
    m = _search(r"([\d.]+)\s*minutes", text)
    if m:
        return {"found": True, "value": float(m.group(1)), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_batt_ambient(text):
    m = _search(r"(-?\d+)\s*C\s*to\s*(\d+)\s*C", text)
    if m:
        return {"found": True, "value": (float(m.group(1)), float(m.group(2))), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_crah_humidity(text):
    m = _search(r"(\d+)\s*%\s*to\s*(\d+)\s*%", text)
    if m:
        return {"found": True, "value": (float(m.group(1)), float(m.group(2))), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


def extract_crah_supply_air_temp(text):
    m = _search(r"supply air temp\w*[^0-9]{0,20}([\d.]+)\s*C", text)
    if m:
        return {"found": True, "value": float(m.group(1)), "raw_evidence": m.group(0)}
    return {"found": False, "value": None, "raw_evidence": ""}


EXTRACTORS = {
    "REQ-UPS-001": extract_ups_efficiency,
    "REQ-UPS-002": extract_ups_voltage,
    "REQ-UPS-003": extract_ups_topology,
    "REQ-CHILL-001": extract_chiller_draw,
    "REQ-CHILL-002": extract_chiller_supply_temp,
    "REQ-CHILL-003": extract_chiller_redundancy,
    "REQ-GEN-001": extract_gen_transfer_time,
    "REQ-GEN-002": extract_gen_speed,
    "REQ-GEN-003": extract_gen_emissions,
    "REQ-BATT-001": extract_batt_autonomy,
    "REQ-BATT-002": extract_batt_ambient,
    "REQ-CRAH-001": extract_crah_humidity,
    "REQ-CRAH-002": extract_crah_supply_air_temp,
}


def _num(pattern, s):
    m = re.search(pattern, s)
    return float(m.group(1)) if m else None


def classify_ups_efficiency(extracted, client_value):
    threshold = _num(r"([\d.]+)", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state measured efficiency."
    val = extracted["value"]
    if val >= threshold:
        return "Compliant", f"{val} %", f"Meets or exceeds the {threshold}% mandate."
    return "Non-Compliant", f"{val} %", f"Measured efficiency ({val}%) is below the {threshold}% mandate."


def classify_ups_voltage(extracted, client_value):
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not confirm input voltage/frequency."
    return "Compliant", extracted["value"], "Matches client input power specification."


def classify_ups_topology(extracted, client_value):
    if not extracted["found"]:
        return "Missing Information", None, "Vendor submittal does not confirm topology / Tier III compliance."
    return "Compliant", extracted["value"], "Vendor document references Tier III / concurrently maintainable topology."


def classify_chiller_draw(extracted, client_value):
    threshold = _num(r"([\d.]+)", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state compressor power draw."
    val = extracted["value"]
    if val <= threshold:
        return "Compliant", f"{val} kW", f"Within the {threshold} kW ceiling."
    return "Non-Compliant", f"{val} kW", f"Exceeds the {threshold} kW ceiling by {round(val - threshold, 1)} kW."


def classify_chiller_supply_temp(extracted, client_value):
    target = _num(r"([\d.]+)", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not confirm chilled water supply temperature."
    val = extracted["value"]
    if abs(val - target) <= 0.5:
        return "Compliant", f"{val} C", f"Within tolerance of the {target} C design target."
    return "Non-Compliant", f"{val} C", f"Outside tolerance of the {target} C design target."


def classify_chiller_redundancy(extracted, client_value):
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state redundancy configuration."
    val = extracted["value"]
    if val == "N+1":
        return "Compliant", val, "Matches the mandatory N+1 redundancy requirement."
    if "upgrade" in val.lower():
        return "Partial Compliance", val, "Base offer ships as N; N+1 only available as a chargeable field upgrade."
    return "Non-Compliant", val, "Vendor offer does not meet N+1 redundancy requirement."


def classify_gen_transfer_time(extracted, client_value):
    ceiling = _num(r"([\d.]+)", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state ATS transfer time."
    val = extracted["value"]
    if val <= ceiling:
        return "Compliant", f"{val} s", f"Within the {ceiling}s ceiling."
    return "Non-Compliant", f"{val} s", f"Exceeds the {ceiling}s ceiling."


def classify_gen_speed(extracted, client_value):
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state governed engine speed."
    return "Compliant", extracted["value"], "Matches the 1500 RPM / 50Hz client mandate."


def classify_gen_emissions(extracted, client_value):
    if not extracted["found"]:
        return "Missing Information", None, "Vendor manual does not address emissions compliance."
    return "Compliant", extracted["value"], "Emissions compliance confirmed in vendor documentation."


def classify_batt_autonomy(extracted, client_value):
    mandate = _num(r"([\d.]+)", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state discharge autonomy."
    val = extracted["value"]
    if val >= mandate:
        return "Compliant", f"{val} min", f"Exceeds the {mandate}-minute mandate."
    return "Non-Compliant", f"{val} min", f"Below the {mandate}-minute mandate."


def classify_batt_ambient(extracted, client_value):
    m = re.search(r"([\d.]+)\s*C\s*\+/-\s*([\d.]+)\s*C", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state ambient operating rating."
    lo_v, hi_v = extracted["value"]
    display = f"{lo_v} C to {hi_v} C"
    if m:
        center, tol = float(m.group(1)), float(m.group(2))
        design_lo, design_hi = center - tol, center + tol
        if lo_v == design_lo and hi_v == design_hi:
            return "Compliant", display, f"Vendor's rated range exactly matches the {design_lo}-{design_hi} C design band."
        return "Non-Compliant", display, (
            f"Vendor's rated range ({display}) is wider than and conflicts with the "
            f"client's tighter {design_lo}-{design_hi} C design point; site HVAC control "
            "is designed around the narrower client band, not the vendor's commercial rating."
        )
    return "Partial Compliance", display, "Could not fully verify against client tolerance band."


def classify_crah_humidity(extracted, client_value):
    m = re.search(r"(\d+)%\s*-\s*(\d+)%", client_value)
    if not extracted["found"]:
        return "Missing Information", None, "Vendor document does not state humidity range."
    lo_v, hi_v = extracted["value"]
    display = f"{lo_v}% - {hi_v}%"
    if m:
        lo_c, hi_c = float(m.group(1)), float(m.group(2))
        if lo_v <= lo_c and hi_v >= hi_c:
            return "Compliant", display, f"Vendor range is a superset of the {lo_c}%-{hi_c}% client spec."
        return "Partial Compliance", display, "Vendor range only partially overlaps the client spec."
    return "Partial Compliance", display, "Could not fully verify against client spec."


def classify_crah_supply_air_temp(extracted, client_value):
    if not extracted["found"]:
        return "Missing Information", None, "Vendor manual is silent on supply air temperature capability."
    return "Compliant", f"{extracted['value']} C", "Matches client setpoint."


CLASSIFIERS = {
    "REQ-UPS-001": classify_ups_efficiency,
    "REQ-UPS-002": classify_ups_voltage,
    "REQ-UPS-003": classify_ups_topology,
    "REQ-CHILL-001": classify_chiller_draw,
    "REQ-CHILL-002": classify_chiller_supply_temp,
    "REQ-CHILL-003": classify_chiller_redundancy,
    "REQ-GEN-001": classify_gen_transfer_time,
    "REQ-GEN-002": classify_gen_speed,
    "REQ-GEN-003": classify_gen_emissions,
    "REQ-BATT-001": classify_batt_autonomy,
    "REQ-BATT-002": classify_batt_ambient,
    "REQ-CRAH-001": classify_crah_humidity,
    "REQ-CRAH-002": classify_crah_supply_air_temp,
}


def build_equipment_to_vendor_docs(vendor_map_df, vendor_docs_root):
    mapping = {}
    for _, row in vendor_map_df.iterrows():
        doc_paths = []
        for col in ("Datasheet_Doc", "Quotation_Doc"):
            rel = str(row.get(col, "") or "").strip()
            if rel:
                doc_paths.append(os.path.join(vendor_docs_root, rel))
        mapping[row["Equipment_ID"]] = {
            "Vendor_ID": row["Vendor_ID"],
            "doc_paths": doc_paths,
        }
    return mapping


def run_compliance_check(project_root, out_path):
    kb_root = os.path.join(project_root, "09_Compliance_Knowledge_Base")
    vendor_docs_root = os.path.join(project_root, "02_Vendor_Documents")

    requirements_df = pd.read_csv(os.path.join(kb_root, "requirements_register.csv"))
    remediation_df = pd.read_csv(os.path.join(kb_root, "remediation_knowledge_base.csv"))
    vendor_map_df = pd.read_csv(os.path.join(vendor_docs_root, "vendor_equipment_map.csv"))

    eq_to_docs = build_equipment_to_vendor_docs(vendor_map_df, vendor_docs_root)

    text_cache = {}

    def get_text(path):
        if path not in text_cache:
            if os.path.exists(path):
                text, method = extract_pdf_text(path)
                text_cache[path] = text
                print(f"  [read] {os.path.relpath(path, project_root)}  ({method}, {len(text)} chars)")
            else:
                text_cache[path] = ""
        return text_cache[path]

    print(f"Loaded {len(requirements_df)} requirements from requirements_register.csv")
    print("Extracting vendor document text (OCR runs automatically for scanned PDFs)...")

    rows = []
    for _, req in requirements_df.iterrows():
        req_id = req["Requirement_ID"]
        eq_id = req["Equipment_ID"]
        client_value = req["Client_Value"]

        doc_info = eq_to_docs.get(eq_id, {"Vendor_ID": None, "doc_paths": []})
        vendor_id = doc_info["Vendor_ID"]
        combined_text = "\n".join(get_text(p) for p in doc_info["doc_paths"])

        extractor = EXTRACTORS.get(req_id)
        classifier = CLASSIFIERS.get(req_id)
        if extractor is None or classifier is None:
            label, vendor_value, rationale = "Missing Information", None, "No extraction rule defined for this requirement."
        else:
            extracted = extractor(combined_text)
            label, vendor_value, rationale = classifier(extracted, client_value)

        remediation_row = remediation_df[remediation_df["Requirement_ID"] == req_id]
        suggested_action = ""
        if label != "Compliant" and not remediation_row.empty:
            suggested_action = remediation_row.iloc[0]["Suggested_Action"]

        rows.append({
            "Requirement_ID": req_id,
            "Category": req["Category"],
            "Equipment_ID": eq_id,
            "Vendor_ID": vendor_id,
            "Requirement_Text": req["Requirement_Text"],
            "Client_Value": client_value,
            "Vendor_Value": vendor_value,
            "Compliance_Label": label,
            "Rationale": rationale,
            "Criticality": req["Criticality"],
            "Impact": req["Impact"],
            "Probability": req["Probability"],
            "Risk_Score": req["Risk_Score"],
            "Suggested_Action": suggested_action,
        })

    report_df = pd.DataFrame(rows).sort_values("Risk_Score", ascending=False)
    report_df.to_csv(out_path, index=False)

    print(f"\nCompliance report written to: {out_path}")
    print("\nLabel distribution:")
    print(report_df["Compliance_Label"].value_counts().to_string())

    print("\nTop risk items requiring attention (Non-Compliant / Partial / Missing):")
    flagged = report_df[report_df["Compliance_Label"] != "Compliant"]
    for _, r in flagged.iterrows():
        print(f"  [{r['Compliance_Label']}] {r['Requirement_ID']} ({r['Equipment_ID']}, risk={r['Risk_Score']}): {r['Rationale']}")

    gt_path = os.path.join(kb_root, "compliance_ground_truth.csv")
    if os.path.exists(gt_path):
        gt_df = pd.read_csv(gt_path)
        evaluate_against_ground_truth(report_df, gt_df, out_path)

    return report_df


def evaluate_against_ground_truth(report_df, gt_df, out_path):
    merged = report_df.merge(
        gt_df[["Requirement_ID", "Compliance_Label"]],
        on="Requirement_ID", suffixes=("_pred", "_true")
    )
    labels = sorted(set(merged["Compliance_Label_true"]) | set(merged["Compliance_Label_pred"]))

    correct = (merged["Compliance_Label_pred"] == merged["Compliance_Label_true"]).sum()
    total = len(merged)
    print(f"\n=== Evaluation vs ground truth ({total} labeled requirements) ===")
    print(f"Overall accuracy: {correct}/{total} ({100*correct/total:.1f}%)")

    conf = pd.crosstab(
        merged["Compliance_Label_true"], merged["Compliance_Label_pred"],
        rownames=["True"], colnames=["Predicted"], dropna=False
    ).reindex(index=labels, columns=labels, fill_value=0)
    print("\nConfusion matrix:")
    print(conf.to_string())

    metrics_rows = []
    for label in labels:
        tp = ((merged["Compliance_Label_pred"] == label) & (merged["Compliance_Label_true"] == label)).sum()
        fp = ((merged["Compliance_Label_pred"] == label) & (merged["Compliance_Label_true"] != label)).sum()
        fn = ((merged["Compliance_Label_pred"] != label) & (merged["Compliance_Label_true"] == label)).sum()
        support = (merged["Compliance_Label_true"] == label).sum()
        precision = tp / (tp + fp) if (tp + fp) > 0 else float("nan")
        recall = tp / (tp + fn) if (tp + fn) > 0 else float("nan")
        f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else float("nan")
        metrics_rows.append({
            "Label": label, "Support": support,
            "Precision": round(precision, 3) if precision == precision else precision,
            "Recall": round(recall, 3) if recall == recall else recall,
            "F1": round(f1, 3) if f1 == f1 else f1,
        })
    metrics_df = pd.DataFrame(metrics_rows)
    print("\nPer-label precision / recall / F1:")
    print(metrics_df.to_string(index=False))

    macro_f1 = metrics_df["F1"].dropna().mean()
    print(f"\nMacro-averaged F1: {macro_f1:.3f}")

    mismatches = merged[merged["Compliance_Label_pred"] != merged["Compliance_Label_true"]]
    if not mismatches.empty:
        print("\nMismatches (worth reviewing your extraction rules for these):")
        for _, r in mismatches.iterrows():
            print(f"  {r['Requirement_ID']}: predicted={r['Compliance_Label_pred']} vs true={r['Compliance_Label_true']}")
    else:
        print("\nNo mismatches -- every requirement matched its ground-truth label.")

    metrics_out_path = os.path.splitext(out_path)[0] + "_eval_metrics.csv"
    metrics_df.to_csv(metrics_out_path, index=False)
    conf_out_path = os.path.splitext(out_path)[0] + "_confusion_matrix.csv"
    conf.to_csv(conf_out_path)
    print(f"\nSaved per-label metrics to: {metrics_out_path}")
    print(f"Saved confusion matrix to: {conf_out_path}")


def main():
    parser = argparse.ArgumentParser(description="AI Compliance Checker for EPC project documents")
    parser.add_argument("--project-root", default="project_data", help="Path to the project_data folder")
    parser.add_argument("--out", default="compliance_report.csv", help="Output CSV path for the compliance report")
    args = parser.parse_args()

    run_compliance_check(args.project_root, args.out)


if __name__ == "__main__":
    main()